// ReSharper disable IdentifierTypo
namespace BrigandineGEDataEditor.Enums
{
    // TODO Convert to hex.
    public enum Name
    {
        Hervery      = 0,
        Baynock      = 1,
        Squest       = 2,
        Linnuis      = 3,
        Kail         = 4,
        Lothian      = 5,
        Caelsent     = 6,
        Letishnote   = 7,
        Broceliande  = 8,
        Asten        = 9,
        Xanas        = 10,
        Salisbury    = 11,
        Karnabone    = 12,
        Tora         = 13,
        Oltroute     = 14,
        Eorsia       = 15,
        Cadbury      = 16,
        Logres       = 17,
        Lidney       = 18,
        Fato         = 19,
        Orkney       = 20,
        Camelford    = 21,
        Phazard      = 22,
        BaydonHill   = 23,
        Gorule       = 24,
        Alliryme     = 25,
        Kardiff      = 26,
        Flogeru      = 27,
        Listinoise   = 28,
        Jukes        = 29,
        Humber       = 30,
        Senadon      = 31,
        Kelilauns    = 32,
        Damas        = 33,
        Whislind     = 34,
        Thala        = 35,
        Glume        = 36,
        Hadrian      = 37,
        Dilworth     = 38,
        Calmary      = 39,
        Solstheim    = 40,
        DolorousGard = 41,
    }
}